HelpPets/urls.py
from django.conf.urls import url
from django.contrib import admin

from CharityApp import views 

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    url(r'help', views.help, name='help'),
    url(r'adoptions', views.adoption, name='adoption'),
    url(r'reports', views.reports, name='reports'),
    url(r'about', views.about, name='about'),
    url(r'^adoption/(\d+)/', views.pet_detail, name='pet_detail'),
]

CharityApp/models.py
from django.db import models

class Pet(models.Model):
    CITY_CHOICES = [("Kh", "Kharkov"), ("Ki", "Kiev"), ("Od", "Odessa")]
    SEX_CHOICES = [("F", "Female"), ("M", "Male")]
    name = models.CharField(max_length = 100)
    species = models.CharField(max_length = 30)
    breed = models.CharField(max_length = 30, blank = True)
    sex = models.CharField(choices = SEX_CHOICES, max_length = 1)
    age = models.IntegerField(null = True)
    city = models.CharField(choices = CITY_CHOICES, max_length = 2)
    submission_date = models.DateTimeField()
    vaccinations = models.ManyToManyField('Vaccine', blank = True)

class Vaccine(models.Model):
    name = models.CharField(max_length = 50)

    def __str__(self):
        return self.name

class MonthlyReport(models.Model):
    month = models.CharField(max_length = 20)
    year = models.IntegerField()
    pets_resqued = models.IntegerField()
    money_spent = models.IntegerField()
    spends = models.TextField()

CharityApp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import Http404

from .models import Pet
from .models import MonthlyReport

def home(request):
    return render(request, 'home.html')

def help(request):
    return render(request, 'help.html')

def adoption(request):
    pets = Pet.objects.all()

    #return render()
    return render(request, 'adoption.html', {'pets': pets})

def pet_detail(request, id):
    try:
        pet = Pet.objects.get(id=id)
    except Pet.DoesNotExist:
        raise Http404('Pet not found')
    return render(request, 'pet_detail.html', {'pet': pet})

def reports(request):
    reports = MonthlyReport.objects.all()
    return render(request, 'reports.html', {'reports': reports})

def about(request):
    return render(request, 'about.html')

CharityApp/templates/CharityApp/index.html
<html>
<head><title></title></head>

<body>

{{ content }}

</body>
</html>

CharityApp/templates/about.html
{% extends "layout.html" %}
{% load static %}

{% block content %}

    <div id="main">
        <div class="container">
            <div id="main-col">
                <h1>About us</h1>
                <p>
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
                    Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
                    when an unknown printer took a galley of type and scrambled it to make a type specimen book. 
                    It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. 
                    It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, 
                    and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum
                </p>
            </div>
            <div id="sidebar">
                <h3>What do we do?</h3>
                <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, 
                    by injected humour, or randomised words which don't look even slightly believable. 
                    If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden
                    in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, 
                    making this the first true generator on the Internet.</p>
            </div>
        </div>
    </div>
{% endblock content %}

CharityApp/templates/adoption.html
{% extends "layout.html" %}

{% block content %}
<section id="showcaseHelp">
    <div class="container">
        <div id="HelpText">
            <h1> Adopt a nice pet, save its life!</h1>
        </div>
    </div>
</section>


    {% for pet in pets %}
    <div class="AboutText">
        <a href="{% url 'pet_detail' pet.id %}">
            <h2> {{ pet.name|capfirst }} </h2>
        </a>
    </div>
    <div class="FundInfo">
        <div class="container">
            <p> {{pet.species}}</p>
            {% if pet.breed %}
            <p> {{pet.breed}}</p>
            {% endif %}

        </div>
    </div>
  
    {% endfor %}

{% endblock content %}

CharityApp/templates/help.html
{% extends "layout.html" %}
{% load static %}

{% block content %}
<main>
    <section id="showcaseHelp">
        <div class="container">
            <div id="HelpText">
                <h1> They need your help!</h1>
            </div>
        </div>
    </section>

    <section class="AboutText">
        <h2>How can you help pets? </h2>
    </section>

    <section class="FundInfo">
        <section class="container">
            <article>
                Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
            </article>
        </section>
    </section>

    <section class="AboutText">
        <h2> Choose your location and help pets!</h2>
    </section>
    <section class ="FundInfo">
        <section class="container">
            <div id="map"></div>
        </section>
    </section>

</main>

    <script>
        function initMap(){
            var location = {lat: 49.985950, lng: 36.273540};
            var map =  new google.maps.Map(document.getElementById("map"), {
                zoom:12,
                center: location
            });


            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function(position) {
                    var pos = {
                        lat: position.coords.latitude,
                        lng: position.coords.longitude
                    };

                    var marker = new google.maps.Marker({position: pos, map: map});

                });
            } else {

                document.getElementById("map").innerText = "Пожалуйста, включите геолокацию"
            }
        }

        function handleLocationError(browserHasGeolocation, infoWindow, pos) {
            infoWindow.setPosition(pos);
            infoWindow.setContent(browserHasGeolocation ?
                'Error: The Geolocation service failed.' :
                'Error: Your browser doesn\'t support geolocation.');
            infoWindow.open(map);
        }


    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC7RPHpJ19Cg5qCm6io8z114kz_mk4Lk3c&callback=initMap"></script>
{% endblock content %}

CharityApp/templates/home.html
{% extends "layout.html" %}
{% load static %}

{% block content %}
<div id="showcase">
    <div class="container">
        <div id="WelcomeText">
            <h1>Charitable Foundation Help Pets</h1>
            <p>We are responsible, forever, for what we have tamed</p>
        </div>

    </div>

</div>

<div class="AboutText">
    <h2>Who are we?</h2>
</div>
    <div class="FundInfo">
        <div class="container">
            <p>
                We are Charitable Foundation "Help Pets", founded in 2018. We care about animals' lives and save thousands of them every year.
                The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.
            </p>
        </div>
    </div>

    <div id="MainFunc">
            <button class = "funcBtn" onclick="location.href='{% url 'about' %}'"> About us </button>
            <button class = "funcBtn" onclick="location.href='{% url 'reports' %}'"> Reports </button>
            <button class = "funcBtn" onclick="location.href='{% url 'help' %}'"> Help us</button>
    </div>

    <div id="Help">
        <div class="container"> 
            <div class="box" id="box1">
                <img class="box_image" src="{% static 'imgs/box1.jpg' %}">
                <button onclick="location.href='Adopt.html'">Rehome a pet</button>
            </div>
            <div class="box" id="box2">
                <img class="box_image" src="{% static 'imgs/box2.jpg' %}">
                <button onclick="location.href='Rehome.html'">Sponsor a pet</button>
            </div>
            <div class="box" id="box3">
                <img class="box_image" src="{% static 'imgs/box3.jpg' %}">
                <button>Make a donation</button>
            </div>

            <div class="box" id="box4">
                <img class="box_image" src="{% static 'imgs/box4.jpg' %}">
                <button onclick="location.href='Help.html'">Become a volunteer</button>
            </div>
      
        </div>
    </div>

{% endblock content %}

CharityApp/templates/layout.html
 {% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name = "viewport" content="width=device-width">
    <meta name="description" content="Help Pets. We care about animals.">
    <meta name="keywords" content="charity, foundation, help pets, adoption">
    <meta name="author" content="Irina Gorbacheva">
    <title>Help Pets | Home page</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

<body>
    <header class="header">
        <div class="container">
            <img src="{% static 'imgs/footprint.png' %}">
            <div id="logo">
                <h1><span>Help</span> Pets</h1>
            </div>

            <div>
                <button id ="popupclick">Donate</button>
            </div>

            <nav id="navbar" class="topnav">
                <a href="{% url 'home' %}" id="cur">Home</a>
                <a href="{% url 'help' %}">Help</a>
                <a href="{% url 'adoption' %}">Rehoming</a>
                <a href="{% url 'reports' %}">Reports</a>
                <a href="{% url 'about' %}">About us</a>
                <a href="javascript:void(0);" class="icon" onclick="responsive()">
                    <svg width="30" height="30">
                        <path d="M0,5 30,5" stroke="#fff" stroke-width="5"/>
                        <path d="M0,14 30,14" stroke="#fff" stroke-width="5"/>
                        <path d="M0,23 30,23" stroke="#fff" stroke-width="5"/>
                    </svg>
                </a>
            </nav>

        </div>

    </header>

{% block content %}
{% endblock content %}

<footer id="footer">
    <div class="container">

        <div id="foot1">
            <h3>Places</h3>
            <p>Kharkov, Pushkinskaya street 62/2, 61001</p>
            <p>Kiev, Kievskaya street 21, 51385</p>
            <p>Odessa, Deribassovskaya street 5, 81934</p>
        </div>
        <div id="foot2">
            <h2></h2>
            <h3> Contacts</h3>
            <p><a href="http://www.google.com" target="_blank">E-mail: HelpPets@gmail.com</a></p>
            <p>Водафон: +38 099 123 45 67</p>
            <p><a href="http://www.google.com" target="_blank">Telegram: @HelpPets</a></p>
            <p><a href="http://www.google.com" target="_blank">Facebook: facebook.com/helppets</a></p>
        </div>

    </div>

</footer>
<script>
    function responsive() {
        var x = document.getElementById("navbar");
        if (x.className === "topnav") {
            x.className += " responsive";
        } else {
            x.className = "topnav";
        }
    }
</script>
</body>
</html>

CharityApp/templates/pet_detail.html
{% extends "layout.html" %}

{% block content %}

<div class="FundInfo">
    <div class="container">
        <h2> {{ pet.name|capfirst }} </h2>
        <p> {{pet.species}}</p>
        {% if pet.breed %}
        <p> Breed: {{pet.breed}}</p>
        {% endif %}
        <p> City: {{pet.get_city_display }}</p>
        <p>Gender: {{pet.get_sex_display }}</p>
        {% if pet.age %}
        <p>Age: {{pet.age }}</p>
        {% endif %}
        <p>Submitted: {{pet.submission_date}}</p>
        {% if pet.vaccinations.all %}
        <p> Vaccinations:</p>
        <ul>
            {% for vaccination in pet.vaccinations.all %}
            <li> {{vaccination.name}} </li>
            {% endfor %}
        </ul>
        {% endif %}

    </div>
</div>

{% endblock content %}

CharityApp/templates/reports.html
{% extends "layout.html" %}
{% load static %}

{% block content %}
<div class="container">
    <table id="report">
        <tr>
            <th class="title">Year</th>
            <th class="title">Month</th>
            <th class="title">Resqued pets</th>
            <th class="title">Money spent</th>
            <th class="title">Spends</th>
        </tr>
        {% for report in reports %}
            <tr>
                <th>{{report.year}}</th>
                <th>{{report.month}}</th>
                <th>{{report.pets_resqued}}</th>
                <th>{{report.money_spent}}</th>
                <th>{{report.spends}}</th>
            </tr>
        {% endfor %}

    </table>
</div>
{% endblock content %}